version: 2.1
orbs:
  heroku: circleci/heroku@1.1.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main
          requires:
            - build
  scheduled-jobs:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: main
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: main
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only: main
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only: main
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only: main
    jobs:
      - run-bot
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  run-bot:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run bot
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python bot.py
